import {Level} from "../level.js";

// Soubor generuje tools/gen_levels.py (otisk mapy 4d13a038).
// Ruční úpravu generátor podle otisku pozná a soubor nepřepíše;
// vynutit přegenerování jde přepínačem --force.
// První argument = rychlost běhu v % základní rychlosti (100 = BASE_SPEED).
const level18 = new Level(
    {speed: 200, theme: 'jungle'},
    "                                                                                                                                                                                                                                                                                                                                    ",
    "                                                                                                                                                                                                  ######          ##################               ##########                                                                       ",
    "                                                                                                                                                                                                       J                ############                        D                                                                       ",
    "                                                                                                                                                                                                                                ####                        D                                                                       ",
    "                                                            o                                      ###########                                                                                                                     J                        D                                                                       ",
    "                                                                                       ############vvvvvvvvvvv                                                                                           *                                                                                                                          ",
    "                                 *                                      ###############vvvvvvvvvvvv                                                                                                                                                                                                                                 ",
    "                                                      o                 v v v v v v v v                                                         J                                     ##########ooooooo####################DD            *                                                                                          ",
    "                                                                                          *                               *                  ####                    *                ##########ooooooo####################DD                                                                  *                                    ",
    "                                ################                                                                                    #############^^^^^^^                                                                  DDD                                                                                                       ",
    "                                ################                                                                            ########             #######^^^^^oooooo                                                       DDD                                               ***                                           *         ",
    " P                        J     ################            ooooooooooooo              ooooooooooooo             ooooooooooo                          #######^^^^^^       UUU                                             DDD                                              *   *         J                                          ",
    "##################################################      ooooo           ooooo      ooooo           ooooo     ooooo                                         ########^^^^^^ UUU                                                                                      #########################           @             U       F######",
    "##################################################ooooooo                   oooooooo                   ooooooo                                                   ######## UUU                                                                                      #########################oooooooooooooooooooooooooU       F######",
);

export {level18};
