#!/usr/bin/env python3
"""Generátor úrovní pro Cube Runner.

Úrovně se skládají z ručně navržených úseků (viz PATTERNS) a před zápisem se
**ověří simulací** – tentýž pohybový model jako v `js/entities/player.js`
a `js/game.js`. Skript projde prohledáváním všechny možnosti, kdy hráč může
skočit, a pokud level nejde doběhnout do cíle, skončí chybou.

Konstanty níž musí sedět s `js/physics.js`.

Použití:
    python3 tools/gen_levels.py          # přepíše js/levels/level1..10.js
    python3 tools/gen_levels.py --check  # jen ověří, nic nezapisuje
"""

import argparse
import json
import math
import os
import sys

# ---- fyzika (kopie js/physics.js) ----
BASE_SPEED = 8.0
GRAVITY = 48.0
JUMP_SPEED = 15.5
PAD_BOOST = 1.4
MAX_FALL = 40.0
CUBE = 0.94
HIT = 0.58
MAX_SUBSTEP = 0.15
EPS = 1e-6

HEIGHT = 14          # počet řádků mapy (0–11 vzduch, 12–13 podlaha)
GROUND_ROW = 12      # první řádek podlahy

# Snímkové časy, na kterých se level ověřuje (hra běží na proměnném dt)
CHECK_DTS = (1 / 60, 1 / 120, 1 / 144)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ---------------------------------------------------------------- úseky map
def pattern(text):
    """Převede textový blok na 14 řádků mapy ('.' = prázdno)."""
    rows = [line for line in text.strip('\n').split('\n')]
    if len(rows) != HEIGHT:
        raise ValueError(f'úsek musí mít {HEIGHT} řádků, má {len(rows)}')
    width = max(len(r) for r in rows)
    return [r.ljust(width, '.').replace('.', ' ') for r in rows]


PATTERNS = {
    # rozběh se startovní pozicí kostky
    'start': pattern("""
............
............
............
............
............
............
............
............
............
............
............
.P..........
############
############
"""),
    # oddechový rovný úsek
    'flat': pattern("""
........
........
........
........
........
........
........
........
........
........
........
........
########
########
"""),
    'flat*': pattern("""
........
........
........
........
........
........
........
........
........
...*....
........
........
########
########
"""),
    # jeden hrot
    'spike1': pattern("""
............
............
............
............
............
............
............
............
............
............
............
......^.....
############
############
"""),
    # dva hroty vedle sebe
    'spike2': pattern("""
..............
..............
..............
..............
..............
..............
..............
..............
.......*......
..............
..............
......^^......
##############
##############
"""),
    # tři hroty vedle sebe
    'spike3': pattern("""
................
................
................
................
................
................
................
................
........*.......
................
................
.......^^^......
################
################
"""),
    # dva hroty s mezerou – dva skoky za sebou
    'spikepair': pattern("""
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
.....^.......^......
####################
####################
"""),
    # díra v podlaze (3 políčka)
    'pit3': pattern("""
..............
..............
..............
..............
..............
..............
..............
..............
.......*......
..............
..............
..............
######...#####
######...#####
"""),
    # díra v podlaze (4 políčka)
    'pit4': pattern("""
................
................
................
................
................
................
................
................
.........*......
................
................
................
#######....#####
#######....#####
"""),
    # schod vysoký 1 políčko
    'step1': pattern("""
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
......####....
##############
##############
"""),
    # blok vysoký 2 políčka
    'step2': pattern("""
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
........#####.....
........#####.....
##################
##################
"""),
    # schodiště 1 -> 2 políčka
    'stairs': pattern("""
....................
....................
....................
....................
....................
....................
....................
....................
..........*.........
....................
.........#####......
.....#########......
####################
####################
"""),
    # plošina nad hroty – dolů se nesmí
    'platform': pattern("""
..................
..................
..................
..................
..................
..................
..................
..................
.........*........
..................
......######......
......^^^^^^......
##################
##################
"""),
    # nízký strop – skok se zkrátí o náraz hlavou
    'ceiling': pattern("""
....................
....................
....................
....................
....................
....................
....############....
....############....
....############....
....................
....................
.........^..........
####################
####################
"""),
    # strop s visícími hroty – skákat jde jen na volných místech
    'ceilspikes': pattern("""
......................
......................
......................
......................
......................
......................
....##############....
....##############....
....##############....
.......vv.............
......................
............^.........
######################
######################
"""),
    # odrazová plošina přes vysokou zeď
    'pad': pattern("""
......................
......................
......................
......................
......................
......................
......................
......................
.......*..............
.........######.......
.........######.......
....J....######.......
######################
######################
"""),
    # široká propast se skokovým prstencem uprostřed
    'ring': pattern("""
........................
........................
........................
........................
........................
........................
........................
........................
........................
..........oo............
........................
........................
########.......#########
########.......#########
"""),
    # pila na zemi – přeskočit
    'saw': pattern("""
................
................
................
................
................
................
................
................
................
................
................
.......S........
################
################
"""),
    # pily ve vzduchu – proběhnout pod nimi
    'sawair': pattern("""
..................
..................
..................
..................
..................
..................
..................
..................
......S.....S.....
..................
..................
..................
##################
##################
"""),
    # obrácená gravitace: běh po stropě a zpátky
    'gravity': pattern("""
##################################
##################################
..............vv..........D.......
..........................D.......
..................................
..................................
..................................
..................................
..................................
..................................
...U..............................
...U..............................
##################################
##################################
"""),
    # cíl
    'finish': pattern("""
............
............
............
............
............
............
............
............
....*.......
............
............
............
#####F######
#####F######
"""),
}


# Plán úrovní: (rychlost v % základní rychlosti, seznam úseků)
LEVEL_PLAN = [
    (100, ['start', 'flat', 'spike1', 'flat', 'spike1', 'flat*', 'spike2',
           'flat', 'step1', 'flat', 'spike1', 'flat', 'finish']),
    (104, ['start', 'flat', 'spike2', 'flat', 'pit3', 'flat', 'spike1',
           'flat*', 'step1', 'flat', 'spikepair', 'flat', 'finish']),
    (108, ['start', 'flat', 'spike3', 'flat', 'pit3', 'flat', 'step1',
           'flat', 'pit4', 'flat*', 'spike2', 'flat', 'finish']),
    (112, ['start', 'flat', 'saw', 'flat', 'spike2', 'flat', 'step2',
           'flat', 'pit4', 'flat', 'spike3', 'flat*', 'finish']),
    (116, ['start', 'flat', 'spike2', 'flat', 'platform', 'flat', 'saw',
           'flat', 'stairs', 'flat', 'pit4', 'flat*', 'finish']),
    (120, ['start', 'flat', 'sawair', 'flat', 'spike3', 'flat', 'ceiling',
           'flat', 'step2', 'flat', 'spikepair', 'flat*', 'finish']),
    (124, ['start', 'flat', 'pad', 'flat', 'spike2', 'flat', 'platform',
           'flat', 'saw', 'flat', 'pit4', 'flat*', 'finish']),
    (128, ['start', 'flat', 'spike2', 'flat', 'ring', 'flat', 'ceilspikes',
           'flat', 'stairs', 'flat', 'spike3', 'flat*', 'finish']),
    (134, ['start', 'flat', 'gravity', 'flat', 'spike3', 'flat', 'pad',
           'flat', 'sawair', 'flat', 'pit4', 'flat*', 'finish']),
    (140, ['start', 'flat', 'spike3', 'flat', 'gravity', 'flat', 'ring',
           'flat', 'platform', 'flat', 'pad', 'flat', 'saw', 'flat*',
           'spikepair', 'flat', 'finish']),
]


def build(plan):
    """Slepí úseky vedle sebe do jedné mapy."""
    rows = [''] * HEIGHT
    for name in plan:
        part = PATTERNS[name]
        for y in range(HEIGHT):
            rows[y] += part[y]
    # Řádky necháváme stejně dlouhé, ať je mapa ve zdrojáku čitelná jako obrázek
    width = max(len(r) for r in rows)
    return [r.ljust(width) for r in rows]


# ------------------------------------------------------------------ simulace
class Map:
    """Rozparsovaná mapa – stejná pravidla jako js/level.js."""

    def __init__(self, rows):
        self.rows = rows
        self.height = len(rows)
        self.width = max(len(r) for r in rows)
        self.spawn = (1, self.height - 3)
        self.finish_x = self.width
        self.solid = set()
        self.hazard = {}
        self.trigger = {}
        self.saws = []
        self.rings = []

        for y, row in enumerate(rows):
            for x in range(self.width):
                ch = row[x] if x < len(row) else ' '
                if ch == '#':
                    self.solid.add((x, y))
                elif ch == '^':
                    self.hazard[(x, y)] = 'up'
                elif ch == 'v':
                    self.hazard[(x, y)] = 'down'
                elif ch == 'S':
                    self.saws.append((x + 0.5, y + 0.5))
                elif ch == 'J':
                    self.trigger[(x, y)] = 'pad'
                elif ch == 'o':
                    self.trigger[(x, y)] = 'ring'
                    self.rings.append((x, y))
                elif ch == 'D':
                    self.trigger[(x, y)] = 'gravityDown'
                elif ch == 'U':
                    self.trigger[(x, y)] = 'gravityUp'
                elif ch == 'P':
                    self.spawn = (x, y)
                elif ch == 'F':
                    self.finish_x = x

    def is_solid(self, x, y):
        return (x, y) in self.solid


def overlaps_solid(m, x, y):
    half = CUBE / 2
    for ty in range(math.floor(y - half + EPS), math.floor(y + half - EPS) + 1):
        for tx in range(math.floor(x - half + EPS), math.floor(x + half - EPS) + 1):
            if m.is_solid(tx, ty):
                return True
    return False


def box_overlap(x, y, size, bx0, by0, bx1, by1):
    half = size / 2
    return x - half < bx1 and x + half > bx0 and y - half < by1 and y + half > by0


def nearby(x, y):
    for ty in range(math.floor(y - 1), math.floor(y + 1) + 1):
        for tx in range(math.floor(x - 1), math.floor(x + 1) + 1):
            yield tx, ty


def advance(state, press, m, speed, dt):
    """Jeden snímek hry. Vrátí nový stav, None (smrt), nebo 'win'."""
    x, y, vy, grav, on_ground, rings = state

    if press:
        if on_ground:
            vy = -grav * JUMP_SPEED
            on_ground = False
        else:
            for tx, ty in nearby(x, y):
                if (m.trigger.get((tx, ty)) == 'ring' and (tx, ty) not in rings
                        and box_overlap(x, y, CUBE, tx, ty, tx + 1, ty + 1)):
                    rings = rings | {(tx, ty)}
                    vy = -grav * JUMP_SPEED
                    on_ground = False
                    break

    # --- Player.step ---
    fastest = max(speed, abs(vy), 1.0)
    steps = max(1, math.ceil(fastest * dt / MAX_SUBSTEP))
    h = dt / steps
    half = CUBE / 2

    for _ in range(steps):
        vy = max(-MAX_FALL, min(MAX_FALL, vy + grav * GRAVITY * h))

        x += speed * h
        if overlaps_solid(m, x, y):
            return None  # náraz do zdi

        y += vy * h
        on_ground = False
        if overlaps_solid(m, x, y):
            if vy > 0:
                y = math.floor(y + half) - half
                on_ground = grav > 0
            elif vy < 0:
                y = math.floor(y - half) + 1 + half
                on_ground = grav < 0
            vy = 0.0

    # --- Game.update ---
    if y > m.height + 2 or y < -3:
        return None

    for tx, ty in nearby(x, y):
        trig = m.trigger.get((tx, ty))
        if not trig or not box_overlap(x, y, CUBE, tx, ty, tx + 1, ty + 1):
            continue
        if trig == 'pad':
            vy = -grav * JUMP_SPEED * PAD_BOOST
            on_ground = False
        elif trig == 'gravityDown':
            grav = 1
        elif trig == 'gravityUp':
            grav = -1

    for tx, ty in nearby(x, y):
        hz = m.hazard.get((tx, ty))
        if hz == 'up' and box_overlap(x, y, HIT, tx + 0.22, ty + 0.35, tx + 0.78, ty + 1):
            return None
        if hz == 'down' and box_overlap(x, y, HIT, tx + 0.22, ty, tx + 0.78, ty + 0.65):
            return None

    for sx, sy in m.saws:
        dx = max(abs(sx - x) - HIT / 2, 0)
        dy = max(abs(sy - y) - HIT / 2, 0)
        if dx * dx + dy * dy < (0.45 * 0.85) ** 2:
            return None

    if x >= m.finish_x:
        return 'win'

    return (x, y, vy, grav, on_ground, rings)


def solve(rows, speed_pct, dt, press_grid=1, limit=200000):
    """Prohledá všechny možnosti skákání. Vrátí seznam čísel snímků, ve kterých
    stačí skočit, aby se level doběhl do cíle – nebo None, když to nejde.

    `press_grid` omezí stisky jen na každý n-tý snímek – slouží jako test
    hratelnosti: level, který vyžaduje přesnost lepší než ~1/30 s, je nefér.
    """
    m = Map(rows)
    speed = BASE_SPEED * speed_pct / 100
    start = (m.spawn[0] + 0.5, m.spawn[1] + 0.5, 0.0, 1, False, frozenset())
    frontier = [start]
    history = []  # historie[snímek] = [(stav, index rodiče, skok?)]
    frames = int(m.width / (speed * dt)) + 600

    def path_to(frame, parent, press):
        """Poskládá zpětně seznam snímků, ve kterých se skákalo."""
        jumps = [frame] if press else []
        idx = parent
        for f in range(frame - 1, -1, -1):
            _, idx, pressed = history[f][idx]
            if pressed:
                jumps.append(f)
        return list(reversed(jumps))

    for frame in range(frames):
        entries = []
        seen = set()
        presses = (False, True) if frame % press_grid == 0 else (False,)

        for parent, st in enumerate(frontier):
            for press in presses:
                res = advance(st, press, m, speed, dt)
                if res is None:
                    continue
                if res == 'win':
                    return path_to(frame, parent, press)
                key = (round(res[1] * 128), round(res[2] * 64), res[3], res[4], res[5])
                if key in seen:
                    continue
                seen.add(key)
                entries.append((res, parent, press))

        if not entries:
            return None
        if len(entries) > limit:
            entries = entries[:limit]
        history.append(entries)
        frontier = [e[0] for e in entries]

    return None


# ------------------------------------------------------------------- výstup
TEMPLATE = '''import {{Level}} from "../level.js";

// první argument = rychlost běhu v % základní rychlosti (100 = BASE_SPEED)
// Soubor generuje tools/gen_levels.py – ruční úpravy přepíše.
const level{n} = new Level(
    {speed},
{rows}
);

export {{level{n}}};
'''


def js_source(n, speed, rows):
    body = '\n'.join('    "%s",' % r.replace('\\', '\\\\').replace('"', '\\"') for r in rows)
    return TEMPLATE.format(n=n, speed=speed, rows=body)


def main():
    parser = argparse.ArgumentParser(description='Vygeneruje a ověří úrovně Cube Runner.')
    parser.add_argument('--check', action='store_true', help='jen ověřit průchodnost, nezapisovat')
    parser.add_argument('--paths', metavar='SOUBOR',
                        help='zapíše do JSON souboru ("-" = na výstup) čísla snímků, ve kterých '
                             'se má skočit, aby se level doběhl (vstup pro tools/playtest.mjs)')
    args = parser.parse_args()

    out_dir = os.path.join(ROOT, 'js', 'levels')
    os.makedirs(out_dir, exist_ok=True)
    failed = False
    paths = []

    for i, (speed, plan) in enumerate(LEVEL_PLAN, start=1):
        rows = build(plan)
        width = max(len(r) for r in rows)

        results = [solve(rows, speed, dt) for dt in CHECK_DTS]
        # Hratelnost: projde level i tomu, kdo mačká jen 30× za sekundu?
        fair = solve(rows, speed, 1 / 120, press_grid=4)

        ok = all(r is not None for r in results) and fair is not None
        status = 'OK ' if ok else 'CHYBA'
        report = ', '.join('ano' if r is not None else 'ne' for r in results)
        print(f'level{i:<2} rychlost {speed:>3} %  šířka {width:>3}  {status} '
              f'(dt: {report}; hratelnost: {"ano" if fair is not None else "ne"})',
              file=sys.stderr if args.paths == '-' else sys.stdout)

        if not ok:
            failed = True
            continue

        # Pro playtest posíláme cestu s hrubým rastrem stisků (nejvíc rezervy)
        paths.append({'level': i, 'speed': speed, 'dt': 1 / 120, 'jumps': fair})

        if not args.check and not args.paths:
            path = os.path.join(out_dir, f'level{i}.js')
            with open(path, 'w', encoding='utf-8') as f:
                f.write(js_source(i, speed, rows))

    if failed:
        print('\nNěkterý level nejde doběhnout – uprav PATTERNS nebo LEVEL_PLAN.', file=sys.stderr)
        return 1

    if args.paths:
        data = json.dumps(paths, indent=1)
        if args.paths == '-':
            print(data)
        else:
            with open(args.paths, 'w', encoding='utf-8') as f:
                f.write(data)
        return 0

    print('\nHotovo.' if not args.check else '\nVšechny úrovně jsou průchozí.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
