#!/usr/bin/env python3
"""Generátor úrovní pro Cube Runner.

Úrovně se skládají z ručně navržených úseků (viz PATTERNS) a před zápisem se
**ověří simulací** – tentýž pohybový model jako v `js/entities/player.js`
a `js/game.js`. Skript projde prohledáváním všechny možnosti, kdy hráč může
skočit, a pokud level nejde doběhnout do cíle, skončí chybou.

Konstanty níž musí sedět s `js/physics.js`.

Použití:
    python3 tools/gen_levels.py          # přepíše js/levels/level1..10.js
    python3 tools/gen_levels.py --check  # jen ověří plán, nic nezapisuje
    python3 tools/gen_levels.py --verify js/levels/level3.js   # ověří hotový soubor
"""

import argparse
import hashlib
import json
import math
import os
import re
import sys

# ---- fyzika (kopie js/physics.js) ----
BASE_SPEED = 8.0
GRAVITY = 48.0
JUMP_SPEED = 15.5
PAD_BOOST = 1.4
MAX_FALL = 40.0
CUBE = 0.94
HIT = 0.58
SAW_HIT = 0.45 * 0.85
ORBIT_RADIUS = 1.2      # kopie js/entities/orbiter.js
ORBIT_SPEED = 2.2
BALL_HIT = 0.4 * 0.9
MAX_SUBSTEP = 0.15
EPS = 1e-6

HEIGHT = 14          # počet řádků mapy (0–11 vzduch, 12–13 podlaha)
GROUND_ROW = 12      # první řádek podlahy

# Snímkové časy, na kterých se level ověřuje (hra běží na proměnném dt)
CHECK_DTS = (1 / 60, 1 / 120, 1 / 144)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ---------------------------------------------------------------- úseky map
def pattern(text):
    """Převede textový blok na 14 řádků mapy ('.' = prázdno)."""
    rows = [line for line in text.strip('\n').split('\n')]
    if len(rows) != HEIGHT:
        raise ValueError(f'úsek musí mít {HEIGHT} řádků, má {len(rows)}')
    width = max(len(r) for r in rows)
    return [r.ljust(width, '.').replace('.', ' ') for r in rows]


PATTERNS = {
    # rozběh se startovní pozicí kostky
    'start': pattern("""
............
............
............
............
............
............
............
............
............
............
............
.P..........
############
############
"""),
    # oddechový rovný úsek
    'flat': pattern("""
........
........
........
........
........
........
........
........
........
........
........
........
########
########
"""),
    'flat*': pattern("""
......
......
......
......
......
......
......
......
......
..*...
......
......
######
######
"""),
    # jeden hrot
    'spike1': pattern("""
........
........
........
........
........
........
........
........
........
........
........
...^....
########
########
"""),
    # dva hroty vedle sebe
    'spike2': pattern("""
..........
..........
..........
..........
..........
..........
..........
..........
..........
....*.....
..........
...^^.....
##########
##########
"""),
    # tři hroty vedle sebe
    'spike3': pattern("""
............
............
............
............
............
............
............
............
............
.....*......
............
....^^^.....
############
############
"""),
    # dva hroty s mezerou – dva skoky za sebou
    'spikepair': pattern("""
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..^.....^.....
##############
##############
"""),
    # díra v podlaze (3 políčka)
    'pit3': pattern("""
...........
...........
...........
...........
...........
...........
...........
...........
...........
.....*.....
...........
...........
####...####
####...####
"""),
    # díra v podlaze (4 políčka)
    'pit4': pattern("""
.............
.............
.............
.............
.............
.............
.............
.............
.............
......*......
.............
.............
####....#####
####....#####
"""),
    # schod vysoký 1 políčko
    'step1': pattern("""
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...####...
##########
##########
"""),
    # blok vysoký 2 políčka
    'step2': pattern("""
.............
.............
.............
.............
.............
.............
.............
.............
.............
.............
....#####....
....#####....
#############
#############
"""),
    # schodiště 1 -> 2 políčka
    'stairs': pattern("""
....................
....................
....................
....................
....................
....................
....................
....................
..........*.........
....................
.........#####......
.....#########......
####################
####################
"""),
    # plošina nad hroty – dolů se nesmí
    'platform': pattern("""
..................
..................
..................
..................
..................
..................
..................
..................
.........*........
..................
......######......
......^^^^^^......
##################
##################
"""),
    # nízký strop – skok se zkrátí o náraz hlavou
    'ceiling': pattern("""
....................
....................
....................
....................
....................
....................
....############....
....############....
....############....
....................
....................
.........^..........
####################
####################
"""),
    # strop s visícími hroty – skákat jde jen na volných místech
    'ceilspikes': pattern("""
......................
......................
......................
......................
......................
......................
....##############....
....##############....
....##############....
.......vv.............
......................
............^.........
######################
######################
"""),
    # odrazová plošina přes vysokou zeď
    'pad': pattern("""
......................
......................
......................
......................
......................
......................
......................
......................
.......*..............
.........######.......
.........######.......
....J....######.......
######################
######################
"""),
    # široká propast se skokovým prstencem uprostřed
    'ring': pattern("""
........................
........................
........................
........................
........................
........................
........................
........................
........................
..........oo............
........................
........................
########.......#########
########.......#########
"""),
    # pila na zemi – přeskočit
    'saw': pattern("""
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
....S.....
##########
##########
"""),
    # pily ve vzduchu – proběhnout pod nimi
    'sawair': pattern("""
.............
.............
.............
.............
.............
.............
.............
.............
...S.....S...
.............
.............
.............
#############
#############
"""),
    # Obrácená gravitace: portál se dá přeskočit, takže překážky musí být
    # na obou stranách – kdo se otočí, řeší strop, kdo ne, řeší podlahu.
    'gravity': pattern("""
################################################################
################################################################
....................vv..........###.........vv........D.........
................................###.............................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
......U.......^^..........................^^^.......^^..........
##########################....##################################
##########################....##################################
"""),
    # --- úseky podle ručních úprav v levelech 1–3 ---
    # plovoucí plošiny nad hroty – skáče se z jedné na druhou
    'islands': pattern("""
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
......####....####......
..........^^^^..........
########################
########################
"""),
    # hroty visící z plovoucích bloků – tudy se běží, ale neskáče
    'hangers': pattern("""
........................
........................
........................
........................
........................
........................
........................
........................
........................
.....###.....###........
.....vvv.....vvv........
...................^....
########################
########################
"""),
    # blok s hroty nahoře i dole – proběhnout pod ním a pak skočit
    'sandwich': pattern("""
....................
....................
....................
....................
....................
....................
....................
........^^..........
........##..........
........vv..........
....................
...............^....
####################
####################
"""),
    # hroty a hned za nimi nízká zeď, po které se běží dál
    'wallrun': pattern("""
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
..............^.........
....^^^#############....
########################
########################
"""),
    # odrazová plošina přes hroty rovnou na vysokou zeď
    'padwall': pattern("""
......................
......................
......................
......................
......................
......................
......................
......................
........#######.......
........#######.......
........#######.......
...J^^^^#######.......
######################
######################
"""),
    # hroty ze země a ze stropu – pozdní skok narazí do stropu
    'zigzag': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
.......vv........vv.......
..........................
...^........^........^....
##########################
##########################
"""),
    # oblouk mincí přes propast – kopíruje dráhu skoku
    'coinarc': pattern("""
......................
......................
......................
......................
......................
......................
......................
......................
......................
........***...........
.......*...*..........
......................
######....############
######....############
"""),
    # mince přímo nad hrotem – odměna za skok ve správnou chvíli
    'spikecoin': pattern("""
..........
..........
..........
..........
..........
..........
..........
..........
..........
....*.....
..........
....^.....
##########
##########
"""),
    # věž ze schodů nahoru a zase dolů
    'towers': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........####............
......############........
......################....
##########################
##########################
"""),
    # pila nad propastí
    'sawgap': pattern("""
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
.........S..........
....................
#######....#########
#######....#########
"""),
    # krátký oddech mezi navazujícími překážkami
    'flat4': pattern("""
....
....
....
....
....
....
....
....
....
....
....
....
####
####
"""),
    # rozcestí: dole se jen skáče přes hroty, nahoře jsou mince navíc
    'fork': pattern("""
................................
................................
................................
................................
................................
................................
................................
................................
............****................
...........#######..............
................................
.....####..............^^^......
################################
################################
"""),
    # past: odrazová plošina vymrští kostku rovnou do hrotů, musí se přeskočit
    'padtrap': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
.......vvvvv..............
..........................
..............*...........
..........................
......J...................
##########################
##########################
"""),
    # mince hned za hrotem – jde získat jen přesným doskokem
    'coinrisk': pattern("""
............
............
............
............
............
............
............
............
............
............
............
....^*......
############
############
"""),
    # nízká chodba: strop zkracuje skok a visící hroty určují, kde se nesmí
    'corridor': pattern("""
............................
............................
............................
............................
............................
............................
............................
............................
....####################....
....####################....
...........vv...............
........^..........^........
############################
############################
"""),
    # tři pily za sebou – rytmus bez oddechu
    'sawrun': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
.....S......S......S......
##########################
##########################
"""),
    # vyvýšená cesta nad hroty s mezerou uprostřed
    'highroad': pattern("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
....########....########........
....^^^^^^^^^^^^^^^^^^^^........
################################
################################
"""),
    # hrot, propast a hrot těsně za sebou
    'chain': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
....^.............^.......
##########...#############
##########...#############
"""),
    # dvě propasti s ostrůvkem mezi nimi
    'doublepit': pattern("""
............................
............................
............................
............................
............................
............................
............................
............................
..............*.............
............................
............................
............................
######...####...############
######...####...############
"""),
    # schod, na kterém navíc stojí hrot
    'spiketower': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........^..............
........##########........
##########################
##########################
"""),
    # obíhající koule na řetězu – podle fáze buď podběhnout, nebo přeskočit
    'orbit': pattern("""
................
................
................
................
................
................
................
................
................
................
.......@........
................
################
################
"""),
    # dvě koule za sebou, každá v jiné fázi
    'orbit2': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
......@...........@.......
..........................
##########################
##########################
"""),
    # vyvýšený terén, po kterém se chvíli běží (a jsou na něm hroty)
    'highground': pattern("""
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..........^.........^.........
.....####################.....
.....####################.....
##############################
##############################
"""),
    # most z ostrůvků nad propastí – doskoky z bloku na blok
    'bridge': pattern("""
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
........###....###....###.......
######..................########
######..................########
"""),
    # dlouhá nízká chodba – strop krátí skok a hroty nutí skákat pořád
    'tunnel': pattern("""
............................
............................
............................
............................
............................
............................
...####################.....
...####################.....
...####################.....
............................
............................
.......^......^......^......
############################
############################
"""),
    # schody nahoru a dolů, na každém patře hrot
    'plateau': pattern("""
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.............^................
........#############.........
....#####################.....
....#####################.....
##############################
##############################
"""),
    # obíhající koule přesně nad propastí
    'orbitgap': pattern("""
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
.........@..........
....................
#######....#########
#######....#########
"""),
    # schodiště, na kterém stojí hroty
    'spikestair': pattern("""
......................
......................
......................
......................
......................
......................
......................
......................
......................
............^.........
.........########.....
....############......
######################
######################
"""),
    # Supi nad stolovou horou (pouštní téma kreslí hroty ze stropu jako supy):
    # nahoru se musí vyskočit, po hoře se běží pod nimi a skáče se jen nad roklí,
    # kde žádný sup nevisí.
    'vulturemesa': pattern("""
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
........vv........vv......
..........................
....########...########...
....########...########...
##########################
##########################
"""),
    # Supi nad rovinou: pod nimi se nesmí vyskočit, takže hrot i propast se
    # musí přeskočit z místa mezi nimi.
    'vulturegap': pattern("""
............................
............................
............................
............................
............................
............................
............................
............................
............................
....vv...........vv.........
............................
.........^..................
#####################....###
#####################....###
"""),
    # Povinná gravitace: vstupní portál je tři políčka vysoký (nejde přeskočit)
    # a výstupní je o řádek pod dráhou, takže se do něj musí záměrně klesnout –
    # kdo to nestihne, vyletí na konci stropu z mapy.
    'gravitylock': pattern("""
########################################################
########################################################
..................vv..........###..........vv...........
..............................###...............D.......
........................................................
........................................................
........................................................
........................................................
........................................................
......U.................................................
......U.................................................
......U.................................................
########################################################
########################################################
"""),
    # cíl
    'finish': pattern("""
............
............
............
............
............
............
............
............
....*.......
............
............
............
#####F######
#####F######
"""),
}


# Plán úrovní: (rychlost v % základní rychlosti, seznam úseků).
#
# Každá úroveň stojí na vlastní sadě úseků, které se jinde skoro neobjeví –
# jinak si jsou kola podobná, i když mají jiné pořadí. Obecné hroty slouží jen
# jako spojovací materiál, ne jako náplň. Hustotu určuje šířka oddechu:
# `flat` (8 políček) na začátku a konci, `flat4` (4) mezi překážkami.
LEVEL_PLAN = [
    # 1 – základy: hroty, schody, první rozcestí
    (100, ['start', 'flat', 'spike1', 'flat4', 'spikecoin', 'flat4', 'step1',
           'flat4', 'spike2', 'flat4', 'coinrisk', 'flat4', 'plateau',
           'flat4', 'spike3', 'flat4', 'fork', 'flat4', 'spikepair', 'flat4',
           'step1', 'flat4', 'spike2', 'flat', 'finish']),
    # 2 – propasti: díry, mosty a doskoky
    (106, ['start', 'flat', 'pit3', 'flat4', 'spike2', 'flat4', 'pit4',
           'flat4', 'coinarc', 'flat4', 'chain', 'flat4', 'bridge', 'flat4',
           'doublepit', 'flat4', 'spikepair', 'flat4', 'pit4', 'flat4',
           'coinrisk', 'flat4', 'chain', 'flat', 'finish']),
    # 3 – poušť s terénem: běh po zdech, ostrůvcích a stolových horách se supy
    (112, ['start', 'flat', 'wallrun', 'flat4', 'spiketower', 'flat4',
           'islands', 'flat4', 'highground', 'flat4', 'vulturemesa', 'flat4',
           'highroad', 'flat4', 'step2', 'flat4', 'stairs', 'flat4', 'fork',
           'flat4', 'vulturemesa', 'flat4', 'plateau', 'flat', 'finish']),
    # 4 – všechno, co se hýbe: pily a koule na řetězu
    (118, ['start', 'flat', 'saw', 'flat4', 'sawair', 'flat4', 'orbit',
           'flat4', 'sawgap', 'flat4', 'spike2', 'flat4', 'sawrun', 'flat4',
           'orbitgap', 'flat4', 'saw', 'flat4', 'orbit2', 'flat4', 'sawair',
           'flat4', 'spikepair', 'flat', 'finish']),
    # 5 – ledová jeskyně: samé stropy a krápníky
    (124, ['start', 'flat', 'ceiling', 'flat4', 'hangers', 'flat4', 'tunnel',
           'flat4', 'sandwich', 'flat4', 'corridor', 'flat4', 'ceilspikes',
           'flat4', 'spike3', 'flat4', 'hangers', 'flat4', 'tunnel', 'flat4',
           'coinrisk', 'flat', 'finish']),
    # 6 – druhá poušť: odrazové plošiny, pasti, stavby a supi nad rovinou
    (130, ['start', 'flat', 'pad', 'flat4', 'spiketower', 'flat4', 'padtrap',
           'flat4', 'platform', 'flat4', 'spikestair', 'flat4', 'padwall',
           'flat4', 'towers', 'flat4', 'vulturegap', 'flat4', 'fork', 'flat4',
           'vulturegap', 'flat', 'finish']),
    # 7 – prstence a široké propasti
    (136, ['start', 'flat', 'ring', 'flat4', 'highground', 'flat4', 'highroad',
           'flat4', 'bridge', 'flat4', 'orbit2', 'flat4', 'coinarc', 'flat4',
           'ring', 'flat4', 'spikecoin', 'flat4', 'islands', 'flat4',
           'spikepair', 'flat', 'finish']),
    # 8 – gravitace: nejdřív povinná, pak taková, co jde přeskočit
    (142, ['start', 'flat', 'gravitylock', 'flat4', 'spike3', 'flat4',
           'zigzag', 'flat4', 'corridor', 'flat4', 'gravity', 'flat4',
           'spikepair', 'flat4', 'tunnel', 'flat4', 'coinrisk', 'flat',
           'finish']),
    # 9 – kombinace všech témat
    (148, ['start', 'flat', 'fork', 'flat4', 'saw', 'flat4', 'plateau',
           'flat4', 'gravitylock', 'flat4', 'sandwich', 'flat4', 'islands',
           'flat4', 'spikestair', 'flat4', 'orbit2', 'flat4', 'chain',
           'flat4', 'wallrun', 'flat', 'finish']),
    # 10 – finále: nejdelší, nejrychlejší a bez oddechu
    (155, ['start', 'flat', 'spike3', 'flat4', 'chain', 'flat4', 'sawrun',
           'flat4', 'tunnel', 'flat4', 'padtrap', 'flat4', 'ring', 'flat4',
           'gravitylock', 'flat4', 'bridge', 'flat4', 'orbit2', 'flat4',
           'highroad', 'flat4', 'gravity', 'flat4', 'plateau', 'flat4',
           'spikestair', 'flat4', 'fork', 'flat4', 'doublepit', 'flat4',
           'spikepair', 'flat', 'finish']),
]


def build(plan):
    """Slepí úseky vedle sebe do jedné mapy."""
    rows = [''] * HEIGHT
    for name in plan:
        part = PATTERNS[name]
        for y in range(HEIGHT):
            rows[y] += part[y]
    # Řádky necháváme stejně dlouhé, ať je mapa ve zdrojáku čitelná jako obrázek
    width = max(len(r) for r in rows)
    return [r.ljust(width) for r in rows]


# ------------------------------------------------------------------ simulace
class Map:
    """Rozparsovaná mapa – stejná pravidla jako js/level.js."""

    def __init__(self, rows):
        self.rows = rows
        self.height = len(rows)
        self.width = max(len(r) for r in rows)
        self.spawn = (1, self.height - 3)
        self.finish_x = self.width
        self.solid = set()
        self.hazard = {}
        self.trigger = {}
        self.saws = []
        self.orbiters = []
        self.rings = []

        for y, row in enumerate(rows):
            for x in range(self.width):
                ch = row[x] if x < len(row) else ' '
                if ch == '#':
                    self.solid.add((x, y))
                elif ch == '^':
                    self.hazard[(x, y)] = 'up'
                elif ch == 'v':
                    self.hazard[(x, y)] = 'down'
                elif ch == 'S':
                    self.saws.append((x + 0.5, y + 0.5))
                elif ch == '@':
                    self.orbiters.append((x + 0.5, y + 0.5))
                elif ch == 'J':
                    self.trigger[(x, y)] = 'pad'
                elif ch == 'o':
                    self.trigger[(x, y)] = 'ring'
                    self.rings.append((x, y))
                elif ch == 'D':
                    self.trigger[(x, y)] = 'gravityDown'
                elif ch == 'U':
                    self.trigger[(x, y)] = 'gravityUp'
                elif ch == 'P':
                    self.spawn = (x, y)
                elif ch == 'F':
                    self.finish_x = x

    def is_solid(self, x, y):
        return (x, y) in self.solid


def overlaps_solid(m, x, y):
    half = CUBE / 2
    for ty in range(math.floor(y - half + EPS), math.floor(y + half - EPS) + 1):
        for tx in range(math.floor(x - half + EPS), math.floor(x + half - EPS) + 1):
            if m.is_solid(tx, ty):
                return True
    return False


def box_overlap(x, y, size, bx0, by0, bx1, by1):
    half = size / 2
    return x - half < bx1 and x + half > bx0 and y - half < by1 and y + half > by0


def nearby(x, y):
    for ty in range(math.floor(y - 1), math.floor(y + 1) + 1):
        for tx in range(math.floor(x - 1), math.floor(x + 1) + 1):
            yield tx, ty


def advance(state, press, m, speed, dt):
    """Jeden snímek hry. Vrátí nový stav, None (smrt), nebo 'win'."""
    x, y, vy, grav, on_ground, rings = state

    if press:
        if on_ground:
            vy = -grav * JUMP_SPEED
            on_ground = False
        else:
            for tx, ty in nearby(x, y):
                if (m.trigger.get((tx, ty)) == 'ring' and (tx, ty) not in rings
                        and box_overlap(x, y, CUBE, tx, ty, tx + 1, ty + 1)):
                    rings = rings | {(tx, ty)}
                    vy = -grav * JUMP_SPEED
                    on_ground = False
                    break

    # --- Player.step ---
    fastest = max(speed, abs(vy), 1.0)
    steps = max(1, math.ceil(fastest * dt / MAX_SUBSTEP))
    h = dt / steps
    half = CUBE / 2

    for _ in range(steps):
        vy = max(-MAX_FALL, min(MAX_FALL, vy + grav * GRAVITY * h))

        x += speed * h
        if overlaps_solid(m, x, y):
            return None  # náraz do zdi

        y += vy * h
        on_ground = False
        if overlaps_solid(m, x, y):
            if vy > 0:
                y = math.floor(y + half) - half
                on_ground = grav > 0
            elif vy < 0:
                y = math.floor(y - half) + 1 + half
                on_ground = grav < 0
            vy = 0.0

    # --- Game.update ---
    if y > m.height + 2 or y < -3:
        return None

    for tx, ty in nearby(x, y):
        trig = m.trigger.get((tx, ty))
        if not trig or not box_overlap(x, y, CUBE, tx, ty, tx + 1, ty + 1):
            continue
        if trig == 'pad':
            vy = -grav * JUMP_SPEED * PAD_BOOST
            on_ground = False
        elif trig == 'gravityDown':
            grav = 1
        elif trig == 'gravityUp':
            grav = -1

    for tx, ty in nearby(x, y):
        hz = m.hazard.get((tx, ty))
        if hz == 'up' and box_overlap(x, y, HIT, tx + 0.22, ty + 0.35, tx + 0.78, ty + 1):
            return None
        if hz == 'down' and box_overlap(x, y, HIT, tx + 0.22, ty, tx + 0.78, ty + 0.65):
            return None

    def hits(cx, cy, radius):
        dx = max(abs(cx - x) - HIT / 2, 0)
        dy = max(abs(cy - y) - HIT / 2, 0)
        return dx * dx + dy * dy < radius * radius

    for sx, sy in m.saws:
        if hits(sx, sy, SAW_HIT):
            return None

    # Koule obíhá kolem kotvy; kostka běží konstantní rychlostí, takže odehraný
    # čas jde spočítat z její x-ové souřadnice (stejně jako `animPhase` ve hře)
    if m.orbiters:
        angle = (x - (m.spawn[0] + 0.5)) / speed * ORBIT_SPEED
        for ax, ay in m.orbiters:
            if hits(ax + math.cos(angle) * ORBIT_RADIUS,
                    ay + math.sin(angle) * ORBIT_RADIUS, BALL_HIT):
                return None

    if x >= m.finish_x:
        return 'win'

    return (x, y, vy, grav, on_ground, rings)


def solve(rows, speed_pct, dt, press_grid=1, limit=200000):
    """Prohledá všechny možnosti skákání. Vrátí seznam čísel snímků, ve kterých
    stačí skočit, aby se level doběhl do cíle – nebo None, když to nejde.

    `press_grid` omezí stisky jen na každý n-tý snímek – slouží jako test
    hratelnosti: level, který vyžaduje přesnost lepší než ~1/30 s, je nefér.
    """
    m = Map(rows)
    speed = BASE_SPEED * speed_pct / 100
    start = (m.spawn[0] + 0.5, m.spawn[1] + 0.5, 0.0, 1, False, frozenset())
    frontier = [start]
    history = []  # historie[snímek] = [(stav, index rodiče, skok?)]
    frames = int(m.width / (speed * dt)) + 600

    def path_to(frame, parent, press):
        """Poskládá zpětně seznam snímků, ve kterých se skákalo."""
        jumps = [frame] if press else []
        idx = parent
        for f in range(frame - 1, -1, -1):
            _, idx, pressed = history[f][idx]
            if pressed:
                jumps.append(f)
        return list(reversed(jumps))

    for frame in range(frames):
        entries = []
        seen = set()
        presses = (False, True) if frame % press_grid == 0 else (False,)

        for parent, st in enumerate(frontier):
            for press in presses:
                res = advance(st, press, m, speed, dt)
                if res is None:
                    continue
                if res == 'win':
                    return path_to(frame, parent, press)
                key = (round(res[1] * 128), round(res[2] * 64), res[3], res[4], res[5])
                if key in seen:
                    continue
                seen.add(key)
                entries.append((res, parent, press))

        if not entries:
            return None
        if len(entries) > limit:
            entries = entries[:limit]
        history.append(entries)
        frontier = [e[0] for e in entries]

    return None


# ------------------------------------------------------------------- výstup
TEMPLATE = '''import {{Level}} from "../level.js";

// Soubor generuje tools/gen_levels.py (otisk mapy {digest}).
// Ruční úpravu generátor podle otisku pozná a soubor nepřepíše;
// vynutit přegenerování jde přepínačem --force.
// První argument = rychlost běhu v % základní rychlosti (100 = BASE_SPEED).
const level{n} = new Level(
    {head},
{rows}
);

export {{level{n}}};
'''

# Vizuální témata úrovní (viz Level v js/level.js). Bez záznamu = běžný vzhled.
LEVEL_THEMES = {
    # Pouštní levely mají v plánu vlastní úsek s hroty ze stropu (vulturemesa,
    # vulturegap) – jinak by se supi ve hře skoro neobjevili.
    3: 'desert',    # poušť – kaktusy, supi, pískovec, duny a rozpálený vzduch
    5: 'ice',       # ledová jeskyně – krápníky, namrzlé bloky, padající sníh
    6: 'desert',
    8: 'fire',      # sopečná sloj – plameny, sopky, láva a chvění horkého vzduchu
    10: 'fire',
}


def fingerprint(speed, rows):
    """Otisk samotné mapy – nemění se přeformátováním komentářů kolem."""
    data = f'{speed}\n' + '\n'.join(rows)
    return hashlib.sha1(data.encode('utf-8')).hexdigest()[:8]


def js_source(n, speed, rows):
    body = '\n'.join('    "%s",' % r.replace('\\', '\\\\').replace('"', '\\"') for r in rows)
    theme = LEVEL_THEMES.get(n)
    head = f"{{speed: {speed}, theme: '{theme}'}}" if theme else str(speed)
    return TEMPLATE.format(n=n, head=head, rows=body, digest=fingerprint(speed, rows))


def hand_edited(path):
    """Byl soubor upraven ručně? (obsah nesedí na otisk v hlavičce)"""
    if not os.path.exists(path):
        return False
    with open(path, encoding='utf-8') as f:
        src = f.read()

    stamp = re.search(r'otisk mapy ([0-9a-f]{8})', src)
    if not stamp:
        return True  # bez otisku nevíme, co v souboru je – radši nepřepisovat
    try:
        speed, rows = read_level_js(path)
    except ValueError:
        return True
    return fingerprint(speed, rows) != stamp.group(1)


def read_level_js(path):
    """Vytáhne ze souboru `js/levels/levelX.js` rychlost a řádky mapy."""
    with open(path, encoding='utf-8') as f:
        src = f.read()

    call = re.search(r'new\s+Level\s*\((.*?)\n\s*\);', src, re.S)
    if not call:
        raise ValueError(f'{path}: nenašel jsem volání new Level(...)')

    body = call.group(1)
    speed = re.search(r'(\d+)', body)
    rows = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
    if not speed or not rows:
        raise ValueError(f'{path}: nepovedlo se přečíst rychlost nebo řádky mapy')

    return int(speed.group(1)), [r.replace('\\\\', '\\').replace('\\"', '"') for r in rows]


def level_files():
    """Soubory s levely v pořadí level1, level2, … (to, co se opravdu hraje)."""
    out_dir = os.path.join(ROOT, 'js', 'levels')
    found = []
    for name in os.listdir(out_dir):
        m = re.fullmatch(r'level(\d+)\.js', name)
        if m:
            found.append((int(m.group(1)), os.path.join(out_dir, name)))
    return [path for _, path in sorted(found)]


def emit_paths(target):
    """Vypíše JSON s čísly snímků, ve kterých se má skočit – pro playtest.

    Počítá se z hotových souborů v js/levels/, ne z plánu, aby to sedělo
    i na ručně upravené mapy.
    """
    result = []
    for i, path in enumerate(level_files(), start=1):
        speed, rows = read_level_js(path)
        jumps = solve(rows, speed, 1 / 120, press_grid=4)
        if jumps is None:
            print(f'{os.path.basename(path)}: level nejde doběhnout', file=sys.stderr)
            return 1
        result.append({'level': i, 'speed': speed, 'dt': 1 / 120, 'jumps': jumps})

    data = json.dumps(result, indent=1)
    if target == '-':
        print(data)
    else:
        with open(target, 'w', encoding='utf-8') as f:
            f.write(data)
    return 0


def verify_files(paths):
    """Ověří průchodnost hotových souborů s levely (i ručně upravených)."""
    failed = False
    for path in paths:
        try:
            speed, rows = read_level_js(path)
        except ValueError as e:
            print(e, file=sys.stderr)
            failed = True
            continue

        results = [solve(rows, speed, dt) for dt in CHECK_DTS]
        fair = solve(rows, speed, 1 / 120, press_grid=4)
        ok = all(r is not None for r in results) and fair is not None
        report = ', '.join('ano' if r is not None else 'ne' for r in results)
        print(f'{os.path.basename(path):<12} rychlost {speed:>3} %  šířka {max(len(r) for r in rows):>3}  '
              f'{"OK " if ok else "CHYBA"} (dt: {report}; hratelnost: {"ano" if fair is not None else "ne"})')
        if not ok:
            failed = True

    if failed:
        print('\nLevel nejde doběhnout do cíle – uprav mapu.', file=sys.stderr)
        return 1
    print('\nVšechny ověřené levely jsou průchozí.')
    return 0


def main():
    parser = argparse.ArgumentParser(description='Vygeneruje a ověří úrovně Cube Runner.')
    parser.add_argument('--check', action='store_true', help='jen ověřit průchodnost, nezapisovat')
    parser.add_argument('--force', action='store_true',
                        help='přepsat i levely upravené ručně')
    parser.add_argument('--verify', nargs='+', metavar='SOUBOR',
                        help='neověřovat plán, ale hotové soubory js/levels/*.js '
                             '(hodí se na ručně upravené mapy)')
    parser.add_argument('--paths', metavar='SOUBOR',
                        help='zapíše do JSON souboru ("-" = na výstup) čísla snímků, ve kterých '
                             'se má skočit, aby se level doběhl (vstup pro tools/playtest.mjs)')
    args = parser.parse_args()

    if args.verify:
        return verify_files(args.verify)

    if args.paths:
        return emit_paths(args.paths)

    out_dir = os.path.join(ROOT, 'js', 'levels')
    os.makedirs(out_dir, exist_ok=True)
    failed = False
    skipped = []

    for i, (speed, plan) in enumerate(LEVEL_PLAN, start=1):
        rows = build(plan)
        width = max(len(r) for r in rows)

        results = [solve(rows, speed, dt) for dt in CHECK_DTS]
        # Hratelnost: projde level i tomu, kdo mačká jen 30× za sekundu?
        fair = solve(rows, speed, 1 / 120, press_grid=4)

        ok = all(r is not None for r in results) and fair is not None
        status = 'OK ' if ok else 'CHYBA'
        report = ', '.join('ano' if r is not None else 'ne' for r in results)
        print(f'level{i:<2} rychlost {speed:>3} %  šířka {width:>3}  {status} '
              f'(dt: {report}; hratelnost: {"ano" if fair is not None else "ne"})',
              )

        if not ok:
            failed = True
            continue

        if not args.check:
            path = os.path.join(out_dir, f'level{i}.js')
            if hand_edited(path) and not args.force:
                skipped.append(os.path.basename(path))
                continue
            with open(path, 'w', encoding='utf-8') as f:
                f.write(js_source(i, speed, rows))

    if failed:
        print('\nNěkterý level nejde doběhnout – uprav PATTERNS nebo LEVEL_PLAN.', file=sys.stderr)
        return 1

    if skipped:
        print('\nNepřepsáno (ruční úprava): ' + ', '.join(skipped) +
              '\nOvěřit je můžeš přes --verify, přepsat přes --force.')

    print('\nHotovo.' if not args.check else '\nVšechny úrovně jsou průchozí.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
